follower_vision:
  ros__parameters:
    marker_type: "aruco"
    aruco_dictionary: "DICT_4X4_50"
    marker_id: 0
    marker_size: 0.10

    image_topic: "/follower/camera/image_raw"
    camera_info_topic: "/follower/camera/camera_info"

    target_visible_topic: "/follower/target_visible"
    target_offset_x_topic: "/follower/target_offset_x"
    target_distance_topic: "/follower/target_distance"
    target_area_topic: "/follower/target_area"

    publish_debug_image: true
    debug_image_topic: "/follower/debug_image"
