follower_platooning:
  ros__parameters:
    platooning_mode: "odom"

    target_distance: 0.45
    min_distance: 0.32
    max_distance: 0.70
    emergency_stop_distance: 0.20

    kp_distance: 0.45
    kp_yaw: 0.80

    max_linear_speed: 0.10
    max_angular_speed: 0.45

    marker_lost_timeout: 0.5
    odom_timeout: 0.5
    heartbeat_timeout: 1.0
    leader_cmd_timeout: 0.5

    enable_reverse: true
    mirror_leader_reverse_turn: true
    leader_cmd_linear_gain: 1.0
    leader_cmd_angular_gain: 1.0
    leader_cmd_reverse_threshold: 0.01
    leader_cmd_turn_threshold: 0.05
    leader_cmd_turn_linear_deadband: 0.02

    target_visible_topic: "/follower/target_visible"
    target_offset_x_topic: "/follower/target_offset_x"
    target_distance_topic: "/follower/target_distance"

    follower_enable_topic: "/leader/follower_enable"
    platoon_mode_topic: "/leader/platoon_mode"
    heartbeat_topic: "/leader/heartbeat"
    leader_cmd_vel_topic: "/leader/cmd_vel"
    leader_odom_topic: "/leader/odom"
    follower_odom_topic: "/odom"

    cmd_vel_raw_topic: "/follower/cmd_vel_raw"
    status_topic: "/follower/status"
    distance_error_topic: "/follower/distance_error"
